# Spring DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/dbdespesas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# configuracoes aplicacao
jwt.application=projeto-tarefas
jwt.secret=41694d66-caef-44fc-8a4b-ef05420de0ea
jwt.expiration=86400000
